# configs/train_config.yaml
experiment:
  name: "call" # "call" or "put" Option for modeling
  description: "PINN for Bitcoin Option Pricing using Mixed Distribution Sampling"

device: "cuda:0"

# ------------------------------------------------------------------------------
# 1. Market Parameters
# ------------------------------------------------------------------------------
market:
  T_MAX: 0.26
  S_range: [0.0, 1000000.0]
  K_range: [10000.0, 500000.0]
  K_step: 1000.0
  t_range: [0.0, 0.26] # 0 - T_MAX
  sigma_range: [0.1, 2.0]
  r_range: [0.0, 0.15]

# ------------------------------------------------------------------------------
# 2. Data Sampling Strategy
# ------------------------------------------------------------------------------
sampling:
  moneyness_range: [0.0, 2.0]    # If Put Option V = 0 (Lower Bound). Its max theoretical value approaches K as S to 0.
  adaptive_std: 1.0              # Same or different focus (default: 1.0)           
  time_sampling_power: 2.0       # Same or different focus (default: 2.0) if 1 is uniform in time

# ------------------------------------------------------------------------------
# 3. Model Architecture
# ------------------------------------------------------------------------------
model:
  n_input: 5
  n_output: 1
  n_hidden: 256
  n_layers: 4
  hidden_activation: "tanh"       # options: "tanh", "silu", "gelu", "relu", "sigmoid"...(default: tanh) 
  output_activation: "softplus"   # options: "softplus", "relu", "identity"...(default: softplus) 

# ------------------------------------------------------------------------------
# 4. Training Hyperparameters
# ------------------------------------------------------------------------------
training:
  mode: "scratch" # Initialize with the original pre-trained model
  epochs: 100000
  lr: 1.0e-4
  
  n_sample_data: 10000
  n_sample_pde_multiplier: 4.0 # (default: 4.0)
  n_sample_kink_multiplier: 0.0 # (default: 0.5)

  # --- Loss Balancing Weights (The Recipe) ---
  # Adjust these to prioritize different aspects of learning
  physics_loss_weight: 1.0   # Base physics law (PDE) (default: 1.0)
  ivp_loss_weight: 20.0      # Initial Condition (t=0), increased priority (default: 20.0)
  bvp_loss_weight: 20.0      # Boundary Condition (S_min, S_max), increased priority (default: 20.0)
  kink_loss_weight: 0.0    # Sharpness at Strike Price (S=K, t=0), highest priority (default: 100.0)
  
  val_interval: 1000         # Evaluate model every val_interval epochs
  n_val_sample: 100000
  n_kink_val_sample: 20000
  checkpoint_epochs: 10000   # Save model checkpoints every checkpoint

# ------------------------------------------------------------------------------
# 5. Validation Fixed Parameters (MOVE OUTSIDE TRAINING)
# ------------------------------------------------------------------------------
validation_params:            
  fix_sigma: 0.5
  fix_r: 0.05